experiments/README.md
experiments/cliff_v1.py
experiments/common.py
experiments/dataset.py
experiments/depth.py
experiments/goodpoint.py
experiments/network.py
experiments/test_skills.py
experiments/train_vision.py
experiments/tree.py
experiments/tree_v1.py
experiments/tree_v2.py
experiments/vgg.py
experiments/vision.py

PR contains code for offline training of image -> per-pixel prediction of block type model

vision model

---

experiments/cliff_v3.py
experiments/common.py
experiments/network.py
experiments/noise.py
experiments/test_skills.py
experiments/transform.py
experiments/tree_v3.py
experiments/vgg.py

noise is from https://github.com/singnet/image-matching

new agent with larger state-history as input

---

examples/5_lumberjack3D.py
experiments/collect_data.py
experiments/dataset.py
experiments/merge_data.py
experiments/train_vision_v2.py
tagilmo/utils/segments.py

new model produces 4 heatmaps: None, log, leaves, coal_ore

sementation network with coal ore

---

examples/5_lumberjack3D.py
examples/neural.py
examples/vis.py
tagilmo/utils/malmo_wrapper.py

Added support for callbacks that don't modify cache + error handling
Moved neural-network code and visualizer to separate files

Refactoring

---

examples/vis.py
experiments/b_tree.py
experiments/common.py
experiments/find_mountain.py
tagilmo/utils/malmo_wrapper.py

Reverts trueagi-io/minecraft-demo#40

Revert "Revert "Experiment with behaviour trees""

---

experiments/find_mountain.py

+ example of running callback on cache change from another callback

use larger resulution in find_mountains

---

tagilmo/utils/malmo_wrapper.py

Since I haven't fixed issues with the last version I worked with stable old commit. Needs review.

Test PR for new features in malmo wrapper 

---

experiments/vereya/test_craft.py
experiments/vereya/test_motion_vereya.py
experiments/vereya/test_vereya.py
tagilmo/utils/malmo_wrapper.py
tagilmo/utils/mission_builder.py

Minor changes to xml generation for Vereya + basic tests

[WIP]Vereya

---

experiments/vereya/test_craft.py
experiments/vereya/test_inventory.py
experiments/vereya/test_motion_vereya.py
experiments/vereya/test_observation.py
experiments/vereya/test_vereya.py
tagilmo/utils/malmo_wrapper.py
tagilmo/utils/malmoutils.py
tagilmo/utils/mission_builder.py

Vereya-specific code + tests
depends on https://github.com/trueagi-io/Vereya/pull/2

merge vereya branch

---

experiments/get_recipes_from_minecraft_data.py

Still figuring out how to find and correctly match variant ids with subtype block entities. In 1.18 it's a bit different but there is still no info on that topic. It's currently done in a 'dummy' way for internal use only. But all filtering procedures are independent of how ids and real entities were associated.

Advanced ingredients processing added

---

experiments/vereya/test_observation.py

Some problems with getting chat content. @noskill please check. We've added new test and it fails.

Chat problems

---

examples/Vereya/6_achiever.py
examples/Vereya/skills.py
tagilmo/utils/malmo_wrapper.py

So, we've discussed with Anatoly current fix to prevent getchat from ruining agent's work, and Anatoly suggested a better solution. Here it is

Better fix for getchat

---

examples/Vereya/7_explorer.py
examples/Vereya/minelogy.py

Explorer is now working with Vereya.

Explorer to vereya

---

examples/Vereya/minelogy.py

Here is the **current** solution for priority list of items to use as fuel. Any suggestions?
It works but probably this is not the best option.

Fuel priority

---

tagilmo/VereyaPython/agent_host.py
tagilmo/utils/malmo_wrapper.py

code for pr https://github.com/trueagi-io/Vereya/pull/33

get minecraft version from ping xml

---

examples/4_mine_and_craft.py
examples/minelogy.py

As discussed today, I've removed minecraft_data import from mine_and_craft script and tested it. Works for me.

removing minecraft_data from mine_and_craft script

---

examples/4_mine_and_craft.py
examples/5_lumberjack3D.py
examples/6_achiever.py
examples/7_explorer.py
examples/agent.py
examples/minelogy.py
examples/skills.py
tagilmo/utils/vereya_wrapper.py

So, I've added initialization of minelogy using current minecraft game version. It's not the most elegant way as i think (maybe it'll be better to convert minelogy to class and put it to the agent and rob as `self.minelogy`). Also it is necessary to initialize minelogy for every script it will be used. It leads to the problem (see `7_explorer.py` for example), when we need to initialize minelogy twice. Though it is currently works.

minelogy initialization added

---

examples/4_mine_and_craft.py
examples/5_lumberjack3D.py
examples/6_achiever.py
examples/7_explorer.py
examples/minelogy.py
tagilmo/utils/mission_builder.py
tagilmo/utils/vereya_wrapper.py
tests/vereya/test_observation.py

So, I've removed any usage of minecraft_data using item_list i'm getting from the game. To test this PR you need to use my Vereya code from here https://github.com/trueagi-io/Vereya/pull/18

Removing usage of minecraft_data

---

tests/vereya/test_observation.py

chat message disappeared in self.rob.observeProcCached()

fix failure in observation from chat

---

tagilmo/utils/mission_builder.py
tagilmo/utils/vereya_wrapper.py
tests/vereya/test_human.py

example:
[{'time': 26860, 'type': 'key', 'command': 'jump', 'pressed': False}, {'time': 26861, 'type': 'mouse', 'deltaX': 0.0, 'deltaY': -1.0}]
for mouse positive X axis is as usual -> 
positive Y is inverted ↓

test for observation from human

---

examples/skills.py

Little fix and now animals won't be harassed anymore.

now agent not pursuting animals trying to pick them up

---

tagilmo/VereyaPython/agent_host.py

should fix issue with using tagilmo from jupiter and spyder

send mission init in class' event loop

---

examples/6_achiever.py
tagilmo/utils/mission_builder.py
tagilmo/utils/vereya_wrapper.py
tests/vereya/test_observation.py

Here is the PR that tests [these](https://github.com/trueagi-io/Vereya/pull/26) changes. And also contains necessary changes for vereya's PR to work.

ObservationFromTriples changes

---

tests/vereya/test_observation.py

getChat is in can_be_none list, so waitNotNoneObserve doesn't actually wait

fix test observation from chat

---

tests/vereya/test_observation.py

my guess is that chat data disappeared in first self.observeProcCached() call

attempt to fix get chat

---

tests/vereya/base_test.py

@DaddyWesker should fix recent failure in pr

fix getTestName

---

tests/vereya/run_tests.py
tests/vereya/test_motion_vereya.py

test to ensure the agent is able to move after the mission start

add tests for motion

---

examples/skills.py
tagilmo/utils/vereya_wrapper.py
tests/vereya/test_observation.py

new tests and minor fixes

---

mcdemoaux/vision/vis.py

I've changed the way it works right now. And edited waitKey's delay. Please check if this variant works.

Update visualizer for Mac

---

tests/vereya/test_consistency.py

Fix test_consistency.py

---

examples/minelogy.py
tagilmo/utils/vereya_wrapper.py

So, this fix is related to problem, when mossy_cobblestone is matched against cobblestone which leads to agent attempt to use this cobblestone in crafting of stone pickaxe which is wrong. 
I know this fix is kinda stubby. But other fix is to rework skill Obtain which i don't know is necessary right now.

fix for mossy_cobblestone

---

examples/4_mine_and_craft.py
examples/6_achiever.py
examples/7_explorer.py
examples/skills.py
tagilmo/utils/mission_builder.py
tagilmo/utils/vereya_wrapper.py

So, I've added new passableBlocks which comes from the game itself. I've tested it and it works as before more or less. This PR should be tested with [this PR](https://github.com/trueagi-io/Vereya/pull/53) from Vereya

Usage of nonsolid blocks from Vereya added

---

tagilmo/VereyaPython/timestamped_video_frame.py

Working with[ this PR](https://github.com/trueagi-io/Vereya/pull/59) only.

Better performance with visualization

---

tagilmo/VereyaPython/timestamped_video_frame.py

Tested with [this PR](https://github.com/trueagi-io/Vereya/pull/64)

slightly better performance

---

.github/workflows/test.yml

saving python and java logs alongside with observations as build artifacts

save all logs and observations as build artifacts

---

tests/vereya/run_tests.py
tests/vereya/test_flat_world.py

@CICS-Oleg 
https://github.com/trueagi-io/Vereya/pull/76

Added test for flat world mission running

---

.github/workflows/test.yml

vUpdate test.yml

---

tagilmo/utils/mission_builder.py
tests/vereya/run_tests.py
tests/vereya/test_quit_from_touching_block.py

Also some additions:
* fixed constructors for DrawingDecorator and AgentQuitFromTouchingBlockType classes
* added methods allowing adding drawing decorators straight into mission
* fixed loading from xml AgentQuitFromTouchingBlockType and RewardForTouchingBlockType handlers
for passing tests requires https://github.com/trueagi-io/Vereya/pull/84
@CICS-Oleg

Added test for AgentQuitFromTouchingBlockType

---

examples/skills.py
tagilmo/VereyaPython/reward_xml.py
tagilmo/utils/mission_builder.py
tagilmo/utils/vereya_wrapper.py
tests/vereya/run_tests.py
tests/vereya/test_reward.py

I noticed rewards were not properly parsed (the resulting reward was always empty)

option for parse_rewards to parse from an xml element
